project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "nypd-arrest-visualization"
  author:
    - Ke Jin (kj2675)
    - Siming Xu (sx2392)
  repo-url: https://github.com/99ning/nypd-arrest-visualization
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


